version: '3.1'

services:
  eureka:
    image: netflixoss/eureka:1.3.1
    ports:
    - "10000:8080"

  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: barberfy
      POSTGRES_PASSWORD: barberfy
      POSTGRES_DB: barberfyschedule
